### ISSUE TITLE
Seems no longer to work

### ISSUE THREAD

**Issue by marbetschar** [d9pouces/SafariWallabag#2]
Despite it alerts that an article was saved to wallabag, the article does not appear there.

**Comment by marbetschar** [comment]
Any chance to get this fixed?

**Comment by paulgit** [comment]
I had the same issue. I disabled and re-enabled the extension in Safari preferences and then I was prompted to trust the extension, after doing so it started working again.

**Comment by marbetschar** [comment]
Lifesaver!!!! It was not directly your issue, but because of your hint I noticed in the extension settings the hint `(with trailing slash)` for the Wallabag URL input field.

Added the trailing `/` to the URL and things started working!
